<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage
    xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore"
    name="TargetModel">
  <eClassifiers
      xsi:type="ecore:EClass"
      name="Class">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="links"
        upperBound="-1"
        eType="#//link"
        containment="true"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="vars"
        upperBound="-1"
        eType="#//vari"
        containment="true"
        eOpposite="#//vari/belongTo"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="vari">
    <eStructuralFeatures
        xsi:type="ecore:EAttribute"
        name="name"
        lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="belongTo"
        eType="#//Class"
        eOpposite="#//Class/vars"/>
  </eClassifiers>
  <eClassifiers
      xsi:type="ecore:EClass"
      name="link">
    <eStructuralFeatures
        xsi:type="ecore:EReference"
        name="linked"
        lowerBound="1"
        upperBound="-1"
        eType="#//vari"/>
  </eClassifiers>
</ecore:EPackage>
