<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uAF" nsURI="http://www.example.org/uAF" nsPrefix="uAF">
  <eClassifiers xsi:type="ecore:EClass" name="Alias" eSuperTypes="#//MeasurableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameOwner" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uafelment" eType="#//UAFElment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" upperBound="-1"
        eType="#//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Defination" eSuperTypes="#//MeasurableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uafelment" eType="#//UAFElment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comment" upperBound="-1"
        eType="#//Comment" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SameAs" eSuperTypes="#//MeasurableElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uafelment" eType="#//UAFElment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependency" upperBound="-1"
        eType="#//Dependency" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment"/>
  <eClassifiers xsi:type="ecore:EClass" name="MeasurableElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="UAFElment"/>
  <eClassifiers xsi:type="ecore:EClass" name="Dependency"/>
</ecore:EPackage>
